lobby:
  world: world
  x: 1
  y: 54
  z: -6
games:
  test:
    world: world
    x: 6
    y: 85
    z: -2
    or:
      - 6,86,-2
      - -11,86,-2
      - -2,86,-34
      - 9,86,-25
      - -14,86,-25
      - 0,98,-11
      - -3,102,15
      - -26,102,-3
      - 2,102,-14
      - -30,70,8
      - -6,68,3
      - -9,76,3
      - 3,76,-9
      - 34,76,-6
      - 15,77,-14
      - 17,77,9
      - -2,79,38
      - -5,82,15
      - -2,77,-25