lobby: 6,86,-2,world
games:
  test:
    lobby: 6,86,-2,world
    spawn:
      - 6,86,-2,world
      - -11,86,-2,world
      - -2,86,-34,world
      - 9,86,-25,world
    or:
      - 6,86,-2,world
      - -11,86,-2,world
      - -2,86,-34,world
      - 9,86,-25,world
      - -14,86,-25,world
      - 0,98,-11,world