main: fr.MatD3mons.BloodyMurder.BloodyMurder
name: BloodyMurder
version: 1.0
author: MatD3mons

commands:
  BloodyMurder:
    description: Permette de voire les différente commande
    aliases: [bm]
permissions:
  BloodyMurder.Help:
    description: give players access to use check commands
  BloodyMurder.Join:
    description: give players access to use check commands
  BloodyMurder.Lobby:
    description: give players access to use check commands
  BloodyMurder.SetEnd:
    description: give players access to use check commands
  BloodyMurder.SetGame:
    description: give players access to use check commands
  BloodyMurder.SetOr:
    description: give players access to use check commands
  BloodyMurder.SetWait:
    description: give players access to use check commands